# Generated by Django 4.1.5 on 2023-03-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admno', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('paremail', models.EmailField(max_length=254)),
                ('phno', models.PositiveBigIntegerField()),
                ('p_phno', models.PositiveBigIntegerField()),
                ('sex', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('l_type', models.CharField(max_length=100)),
                ('l_datefrom', models.DateField()),
                ('l_dateto', models.DateField()),
                ('l_rsn', models.TextField()),
                ('booked_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
