# Generated by Django 4.1.5 on 2023-03-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_alter_student_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='booked_by',
        ),
    ]
