# Generated by Django 4.1.5 on 2023-03-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appauth', '0003_remove_student_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
