# Generated by Django 4.1.5 on 2023-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0004_student_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='closed',
            field=models.BooleanField(null=True),
        ),
    ]
