# Generated by Django 4.1.5 on 2023-03-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_student_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='closed',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
