# Generated by Django 4.1.5 on 2023-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_alter_student_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='permit_allowed',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
